"""add rigor documents

Revision ID: 248df411e06f
Revises: ff74f91f030b
Create Date: 2026-08-01 21:52:25.248101

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '248df411e06f'
down_revision: str | Sequence[str] | None = 'ff74f91f030b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rigor_documents',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('show_id', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('document_status', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('rigor_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rigor_documents_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_rigor_documents_document_status'), ['document_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rigor_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_rigor_documents_show_id'), ['show_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigor_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rigor_documents_show_id'))
        batch_op.drop_index(batch_op.f('ix_rigor_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_rigor_documents_document_status'))
        batch_op.drop_index(batch_op.f('ix_rigor_documents_checksum_sha256'))

    op.drop_table('rigor_documents')
    # ### end Alembic commands ###
