"""add rigor requirements

Revision ID: abbdcd8a40ee
Revises: 248df411e06f
Create Date: 2026-08-02 16:17:59.099339

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'abbdcd8a40ee'
down_revision: str | Sequence[str] | None = '248df411e06f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rigor_requirements',
    sa.Column('requirement_id', sa.String(length=64), nullable=False),
    sa.Column('show_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('requirement_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('requirement_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    with op.batch_alter_table('rigor_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rigor_requirements_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_rigor_requirements_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rigor_requirements_requirement_status'), ['requirement_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rigor_requirements_requirement_type'), ['requirement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_rigor_requirements_show_id'), ['show_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigor_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rigor_requirements_show_id'))
        batch_op.drop_index(batch_op.f('ix_rigor_requirements_requirement_type'))
        batch_op.drop_index(batch_op.f('ix_rigor_requirements_requirement_status'))
        batch_op.drop_index(batch_op.f('ix_rigor_requirements_document_id'))
        batch_op.drop_index(batch_op.f('ix_rigor_requirements_department'))

    op.drop_table('rigor_requirements')
    # ### end Alembic commands ###
