"""add rigor shows

Revision ID: ff74f91f030b
Revises: 0007_scheduled_run_active_index
Create Date: 2026-08-01 19:07:36.096137

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ff74f91f030b'
down_revision: str | Sequence[str] | None = '0007_scheduled_run_active_index'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rigor_shows',
    sa.Column('show_id', sa.String(length=64), nullable=False),
    sa.Column('tour_name', sa.String(length=255), nullable=True),
    sa.Column('artist_or_client', sa.String(length=255), nullable=True),
    sa.Column('show_name', sa.String(length=255), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state_region', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('load_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doors_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('curfew_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("show_status IN ('DOCUMENTS_PENDING', 'INITIAL_REVIEW', 'ADVANCE_IN_PROGRESS', 'NEEDS_CONFIRMATION', 'CONFLICTS_OPEN', 'DEPARTMENT_REVIEW', 'SHOW_READY', 'SHOW_COMPLETE', 'POST_SHOW_REVIEW', 'ARCHIVED')", name='ck_rigor_shows_status'),
    sa.PrimaryKeyConstraint('show_id')
    )
    with op.batch_alter_table('rigor_shows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rigor_shows_show_at'), ['show_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rigor_shows_show_status'), ['show_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rigor_shows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rigor_shows_show_status'))
        batch_op.drop_index(batch_op.f('ix_rigor_shows_show_at'))

    op.drop_table('rigor_shows')
    # ### end Alembic commands ###
