"""Controlled values exposed by the RIGOR application service."""

from enum import StrEnum


class ShowStatus(StrEnum):
    DOCUMENTS_PENDING = "DOCUMENTS_PENDING"
    INITIAL_REVIEW = "INITIAL_REVIEW"
    ADVANCE_IN_PROGRESS = "ADVANCE_IN_PROGRESS"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    CONFLICTS_OPEN = "CONFLICTS_OPEN"
    DEPARTMENT_REVIEW = "DEPARTMENT_REVIEW"
    SHOW_READY = "SHOW_READY"
    SHOW_COMPLETE = "SHOW_COMPLETE"
    POST_SHOW_REVIEW = "POST_SHOW_REVIEW"
    ARCHIVED = "ARCHIVED"


class DocumentType(StrEnum):
    RIDER = "RIDER"
    VENUE_TECHNICAL_PACKAGE = "VENUE_TECHNICAL_PACKAGE"
    FEQ = "FEQ"
    PRODUCTION_SCHEDULE = "PRODUCTION_SCHEDULE"
    LABOR_CALL = "LABOR_CALL"
    RIGGING_PLOT = "RIGGING_PLOT"
    POWER_PLAN = "POWER_PLAN"
    LED_SPECIFICATION = "LED_SPECIFICATION"
    CAMERA_PLOT = "CAMERA_PLOT"
    SIGNAL_FLOW = "SIGNAL_FLOW"
    CONTACT_SHEET = "CONTACT_SHEET"
    EMAIL = "EMAIL"
    CREW_UPDATE = "CREW_UPDATE"
    OTHER = "OTHER"


class DocumentProcessingStatus(StrEnum):
    RECEIVED = "RECEIVED"
    CLASSIFYING = "CLASSIFYING"
    EXTRACTING = "EXTRACTING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


class RequirementOriginType(StrEnum):
    SOURCE_DOCUMENT = "SOURCE_DOCUMENT"
    EMAIL_CONFIRMATION = "EMAIL_CONFIRMATION"
    VERBAL_CONFIRMATION = "VERBAL_CONFIRMATION"
    CREW_UPDATE = "CREW_UPDATE"
    AI_INFERENCE = "AI_INFERENCE"
    HUMAN_ENTRY = "HUMAN_ENTRY"


class RequirementStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    EXTRACTED = "EXTRACTED"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    REQUESTED = "REQUESTED"
    CONFIRMED = "CONFIRMED"
    CONFLICTING = "CONFLICTING"
    REJECTED = "REJECTED"
    CHANGED = "CHANGED"
    RESOLVED = "RESOLVED"
    APPROVED = "APPROVED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
